/**
 * Built-in Palettes
 *
 * Palettes are independent of skins — mix freely.
 * "Pink Millennium Falcon" = falcon skin + pastel palette.
 */

import { colors as ANSI } from '../styles.js';
import type { Palette } from './types.js';

export const PALETTES: Record<string, Palette> = {
  default: {
    name: 'default',
    description: 'Standard dark terminal',
    colors: {
      primary: ANSI.cyan,
      secondary: ANSI.blue,
      accent: ANSI.magenta,
      text: ANSI.white,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.white,
      user: ANSI.green,
      assistant: ANSI.cyan,
      system: ANSI.yellow,
      error: ANSI.red,
      codeKeyword: ANSI.magenta,
      codeString: ANSI.green,
      codeNumber: ANSI.cyan,
      codeComment: ANSI.gray,
      codeFunction: ANSI.yellow,
      diffAdd: ANSI.green,
      diffRemove: ANSI.red,
      diffContext: ANSI.gray,
      success: ANSI.green,
      warning: ANSI.yellow,
      info: ANSI.blue,
      border: ANSI.gray,
      background: '',
      selection: ANSI.bgBlue,
    },
  },

  light: {
    name: 'light',
    description: 'Light terminal backgrounds',
    colors: {
      primary: ANSI.blue,
      secondary: ANSI.cyan,
      accent: ANSI.magenta,
      text: ANSI.black,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.black,
      user: ANSI.blue,
      assistant: ANSI.magenta,
      system: ANSI.gray,
      error: ANSI.red,
      codeKeyword: ANSI.magenta,
      codeString: ANSI.green,
      codeNumber: ANSI.blue,
      codeComment: ANSI.gray,
      codeFunction: ANSI.cyan,
      diffAdd: ANSI.green,
      diffRemove: ANSI.red,
      diffContext: ANSI.gray,
      success: ANSI.green,
      warning: ANSI.yellow,
      info: ANSI.blue,
      border: ANSI.gray,
      background: '',
      selection: ANSI.bgCyan,
    },
  },

  monokai: {
    name: 'monokai',
    description: 'Monokai editor theme',
    colors: {
      primary: ANSI.brightMagenta,
      secondary: ANSI.brightCyan,
      accent: ANSI.brightYellow,
      text: ANSI.white,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.white,
      user: ANSI.brightGreen,
      assistant: ANSI.brightCyan,
      system: ANSI.yellow,
      error: ANSI.brightRed,
      codeKeyword: ANSI.brightMagenta,
      codeString: ANSI.brightYellow,
      codeNumber: ANSI.brightMagenta,
      codeComment: ANSI.gray,
      codeFunction: ANSI.brightGreen,
      diffAdd: ANSI.brightGreen,
      diffRemove: ANSI.brightRed,
      diffContext: ANSI.gray,
      success: ANSI.brightGreen,
      warning: ANSI.brightYellow,
      info: ANSI.brightCyan,
      border: ANSI.gray,
      background: '',
      selection: ANSI.bgGray,
    },
  },

  nord: {
    name: 'nord',
    description: 'Arctic cool tones',
    colors: {
      primary: ANSI.brightCyan,
      secondary: ANSI.blue,
      accent: ANSI.brightMagenta,
      text: ANSI.brightWhite,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.brightWhite,
      user: ANSI.brightCyan,
      assistant: ANSI.brightBlue,
      system: ANSI.yellow,
      error: ANSI.brightRed,
      codeKeyword: ANSI.brightMagenta,
      codeString: ANSI.brightGreen,
      codeNumber: ANSI.brightMagenta,
      codeComment: ANSI.gray,
      codeFunction: ANSI.brightCyan,
      diffAdd: ANSI.brightGreen,
      diffRemove: ANSI.brightRed,
      diffContext: ANSI.gray,
      success: ANSI.brightGreen,
      warning: ANSI.brightYellow,
      info: ANSI.brightBlue,
      border: ANSI.blue,
      background: '',
      selection: ANSI.bgBlue,
    },
  },

  dracula: {
    name: 'dracula',
    description: 'Dracula editor theme',
    colors: {
      primary: ANSI.magenta,
      secondary: ANSI.cyan,
      accent: ANSI.brightMagenta,
      text: ANSI.white,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.white,
      user: ANSI.brightGreen,
      assistant: ANSI.magenta,
      system: ANSI.yellow,
      error: ANSI.brightRed,
      codeKeyword: ANSI.brightMagenta,
      codeString: ANSI.brightYellow,
      codeNumber: ANSI.brightMagenta,
      codeComment: ANSI.gray,
      codeFunction: ANSI.brightGreen,
      diffAdd: ANSI.brightGreen,
      diffRemove: ANSI.brightRed,
      diffContext: ANSI.gray,
      success: ANSI.brightGreen,
      warning: ANSI.brightYellow,
      info: ANSI.cyan,
      border: ANSI.magenta,
      background: '',
      selection: ANSI.bgMagenta,
    },
  },

  solarized: {
    name: 'solarized',
    description: 'Solarized dark',
    colors: {
      primary: ANSI.cyan,
      secondary: ANSI.blue,
      accent: ANSI.yellow,
      text: ANSI.white,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.white,
      user: ANSI.green,
      assistant: ANSI.cyan,
      system: ANSI.yellow,
      error: ANSI.red,
      codeKeyword: ANSI.green,
      codeString: ANSI.cyan,
      codeNumber: ANSI.magenta,
      codeComment: ANSI.gray,
      codeFunction: ANSI.blue,
      diffAdd: ANSI.green,
      diffRemove: ANSI.red,
      diffContext: ANSI.gray,
      success: ANSI.green,
      warning: ANSI.yellow,
      info: ANSI.cyan,
      border: ANSI.cyan,
      background: '',
      selection: ANSI.bgBlue,
    },
  },

  neon: {
    name: 'neon',
    description: 'Cyberpunk neon',
    colors: {
      primary: ANSI.brightGreen,
      secondary: ANSI.brightCyan,
      accent: ANSI.brightMagenta,
      text: ANSI.brightWhite,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.brightWhite,
      user: ANSI.brightGreen,
      assistant: ANSI.brightCyan,
      system: ANSI.brightYellow,
      error: ANSI.brightRed,
      codeKeyword: ANSI.brightMagenta,
      codeString: ANSI.brightGreen,
      codeNumber: ANSI.brightCyan,
      codeComment: ANSI.gray,
      codeFunction: ANSI.brightYellow,
      diffAdd: ANSI.brightGreen,
      diffRemove: ANSI.brightRed,
      diffContext: ANSI.gray,
      success: ANSI.brightGreen,
      warning: ANSI.brightYellow,
      info: ANSI.brightCyan,
      border: ANSI.brightGreen,
      background: '',
      selection: ANSI.bgGreen,
    },
  },

  pastel: {
    name: 'pastel',
    description: 'Soft pastel tones',
    colors: {
      primary: ANSI.brightMagenta,
      secondary: ANSI.brightCyan,
      accent: ANSI.brightYellow,
      text: ANSI.brightWhite,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.brightWhite,
      user: ANSI.brightCyan,
      assistant: ANSI.brightMagenta,
      system: ANSI.brightYellow,
      error: ANSI.brightRed,
      codeKeyword: ANSI.brightMagenta,
      codeString: ANSI.brightCyan,
      codeNumber: ANSI.brightYellow,
      codeComment: ANSI.gray,
      codeFunction: ANSI.brightGreen,
      diffAdd: ANSI.brightGreen,
      diffRemove: ANSI.brightRed,
      diffContext: ANSI.gray,
      success: ANSI.brightGreen,
      warning: ANSI.brightYellow,
      info: ANSI.brightCyan,
      border: ANSI.brightMagenta,
      background: '',
      selection: ANSI.bgMagenta,
    },
  },

  monochrome: {
    name: 'monochrome',
    description: 'Black & white only',
    colors: {
      primary: ANSI.white,
      secondary: ANSI.gray,
      accent: ANSI.white,
      text: ANSI.white,
      textDim: ANSI.gray,
      textBold: ANSI.bold + ANSI.white,
      user: ANSI.white,
      assistant: ANSI.white,
      system: ANSI.gray,
      error: ANSI.white,
      codeKeyword: ANSI.bold + ANSI.white,
      codeString: ANSI.white,
      codeNumber: ANSI.white,
      codeComment: ANSI.gray,
      codeFunction: ANSI.white,
      diffAdd: ANSI.white,
      diffRemove: ANSI.dim + ANSI.white,
      diffContext: ANSI.gray,
      success: ANSI.white,
      warning: ANSI.white,
      info: ANSI.gray,
      border: ANSI.gray,
      background: '',
      selection: ANSI.bgGray,
    },
  },
};
